//! Server-rendered HTML frontend.
//!
//! All pages and fragments are generated by `maud` macros — checked at compile time.
//! `htmx` (loaded from CDN) drives partial swaps and SSE subscriptions; no JS is
//! hand-written except ~30 lines for the stale-banner SSE error handler in `layout.rs`.
//!
//! ## Route responsibilities
//! - `search`  — `GET /`                      → full search page
//! - `search`  — `GET /ui/stations/departures?crs=XXX` → departure board fragment (htmx swap)
//! - `detail`  — `GET /trains/:rid/view`       → full detail page
//! - `detail`  — `GET /ui/trains/:rid/live`    → SSE stream of HTML OOB swap fragments

pub mod charts;
pub mod components;
pub mod dashboard;
pub mod demo;
pub mod detail;
pub mod layout;
pub mod predictions;
pub mod search;
