//! Server-rendered HTML frontend.
//!
//! All pages and fragments are generated by `maud` macros — checked at compile time.
//! `htmx` (loaded from CDN) drives partial swaps and SSE subscriptions; no JS is
//! hand-written except ~30 lines for the stale-banner SSE error handler in `layout.rs`.
//!
//! ## Pages (routes are wired in `api/mod.rs` — the source of truth)
//! - `dashboard`   — `/`                 overview cockpit
//! - `search`      — `/search`           departure board + journey search (+ `/ui/stations/*`, `/ui/journeys`)
//! - `predictions` — `/predictions`      prediction-accuracy analytics
//! - `detail`      — `/trains/:rid/view` train detail (+ `/ui/trains/:rid/live` SSE)
//! - `demo`        — `/demo`             developer console (+ `/ui/demo/*`)
//! - `charts` / `components` / `layout`  shared SVG, fragment, and chrome helpers

pub mod charts;
pub mod components;
pub mod dashboard;
pub mod demo;
pub mod detail;
pub mod layout;
pub mod predictions;
pub mod search;
